<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login__UserName</name>
   <tag></tag>
   <elementGuidId>999b8714-ac71-4f45-863d-0a1df369056f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_UserName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_UserName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;_UserName&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd955668-d0bd-4b2a-9a41-3d4daea7fd0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input100</value>
      <webElementGuid>04da635c-cc48-4269-8df4-8e1429d139b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d565f672-0d9b-4df0-b79f-2d312df2bc3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_UserName</value>
      <webElementGuid>10671e1c-8379-47b1-9c85-2a6993354a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_UserName</value>
      <webElementGuid>5fe7a001-c286-4d71-989a-895ec9bde9b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_UserName&quot;)</value>
      <webElementGuid>e043a032-3160-49ab-81ab-906c53d7c8d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_UserName']</value>
      <webElementGuid>f9d5b309-343f-4866-8da9-651bc031a0fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm_login']/div/input</value>
      <webElementGuid>ae84dae8-0061-4e7f-b454-1f2329cc9923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e8983304-e1a4-4867-85ae-c7a421e8e049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = '_UserName' and @id = '_UserName']</value>
      <webElementGuid>806d3f2d-a83f-406b-8b3b-fc20fa596c1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
