<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_bpjs kesehatan (1)</name>
   <tag></tag>
   <elementGuidId>e6d82807-7a10-4403-9c3d-2a34acfd3d50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui-active-menuitem</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ui-active-menuitem']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ui-active-menuitem</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4fc4c40d-4a2b-4eef-a543-4c141a4c6700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-corner-all ui-state-hover</value>
      <webElementGuid>2ef7902b-7a56-4a1d-98d4-b40d58313ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a5e02c1d-d835-4534-8162-1b00488d741e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-active-menuitem</value>
      <webElementGuid>db0b3ca0-d67e-4b68-bd83-8e4fb9cb0ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>bpjs kesehatan</value>
      <webElementGuid>ac022a31-6370-45de-a1be-86c8d251c76d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-active-menuitem&quot;)</value>
      <webElementGuid>346d6661-8629-47d3-a2d0-0e0cc7b5b49b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ui-active-menuitem']</value>
      <webElementGuid>059486c9-95f9-49a7-85ef-6030438de28a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'bpjs kesehatan')]</value>
      <webElementGuid>71e56c98-9646-4d3a-b3e5-546a49859b0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BPJS Kesehatan'])[1]/following::a[1]</value>
      <webElementGuid>a21014d0-d236-4822-8afa-1316540463e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[2]/following::a[2]</value>
      <webElementGuid>7a809d22-76e6-41e5-a2a6-f4ac2212c3cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BPJS KESEHATAN (IN HEALTH)'])[1]/preceding::a[1]</value>
      <webElementGuid>42a1ed34-d6b2-43ac-b465-c08ce8a9c180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BPJS KESEHATAN CAB TANGERANG'])[1]/preceding::a[2]</value>
      <webElementGuid>5ea12713-4123-4275-8397-46f443370ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='bpjs kesehatan']/parent::*</value>
      <webElementGuid>67e5cc21-fb57-40c4-aec9-e8d921c358f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[4]/li[2]/a</value>
      <webElementGuid>1644b255-4504-4ded-b47a-aa64f3c22d90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ui-active-menuitem' and (text() = 'bpjs kesehatan' or . = 'bpjs kesehatan')]</value>
      <webElementGuid>798dac4e-ada5-4b16-8cf9-02500419fa43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
