<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>font_00409245</name>
   <tag></tag>
   <elementGuidId>039652d1-2984-4de7-89c0-243a91521f3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a > font</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='row00409245']/td/div/a/font</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;00409245&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>773736a9-0a6d-4084-8ac1-9e293948c27c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>green</value>
      <webElementGuid>86412c30-e800-4c70-854e-11ee8e01d5b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>00409245</value>
      <webElementGuid>1b0ce272-e7cf-446f-9a5e-14630b007dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row00409245&quot;)/td[1]/div[1]/a[1]/font[1]</value>
      <webElementGuid>f5c85bf6-0765-4586-b73b-fd144d6a7bd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='row00409245']/td/div/a/font</value>
      <webElementGuid>7b8ce81c-7217-4b71-9ce7-0e28ced378ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[8]/following::font[1]</value>
      <webElementGuid>409b7832-2137-4f6b-8295-418fda22d589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reg.Proses'])[2]/following::font[1]</value>
      <webElementGuid>782d62b1-f6d8-4ebb-915f-a8b82020de56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TONO'])[1]/preceding::font[1]</value>
      <webElementGuid>1524dfec-8b41-4a45-a4ae-aab2db4200da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='L'])[1]/preceding::font[1]</value>
      <webElementGuid>03fb7aab-88f8-4254-a5d6-e65ffab09829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='00409245']/parent::*</value>
      <webElementGuid>b38846d3-3dd6-4e37-94bb-e7507b07a44c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/font</value>
      <webElementGuid>a89deed0-0b66-49f7-972b-ee0138f6e94a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//font[(text() = '00409245' or . = '00409245')]</value>
      <webElementGuid>57b368c0-9691-4774-82f5-4a39c9b2c572</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
