<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No. Induk Karyawan_NIK</name>
   <tag></tag>
   <elementGuidId>95e56179-eaf5-468b-a905-961e413abe00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NIK</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NIK']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#NIK</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4bd91058-1131-4281-a4e3-be1d7357c919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4f4217ed-6bd9-4303-8d3d-3f451582dbe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NIK</value>
      <webElementGuid>9184a171-ba0d-43ec-89ed-cb3473bbfa46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NIK</value>
      <webElementGuid>2ccfbbcc-8932-4c66-8d37-d78fcd8f728e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>faceba78-2c49-4933-9b0c-3eba165b1247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>periksavalidasiangka(this,'alphanum')</value>
      <webElementGuid>b62aebcd-43c0-4d10-b43e-67d6e09e65ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NIK&quot;)</value>
      <webElementGuid>9487f9c8-b8c3-4cd7-bdeb-169173b0e197</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NIK']</value>
      <webElementGuid>cd0aa6a1-eb63-4c72-ba99-04fd66c74889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='_tr_JenisPasien']/td[2]/table/tbody/tr[6]/td[2]/input</value>
      <webElementGuid>28979cfb-5278-4419-a0a1-354a6be41b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr[6]/td[2]/input</value>
      <webElementGuid>e9605a38-318b-44c6-bf57-dbc8776d3932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'NIK' and @name = 'NIK']</value>
      <webElementGuid>29037736-8f31-4e53-9b77-48379fe5d762</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
