<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PerusahaanAfiliasi_NamaPerusahaan</name>
   <tag></tag>
   <elementGuidId>09e277af-7908-4d7e-a96a-2db3b25910af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NamaPerusahaan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NamaPerusahaan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#NamaPerusahaan</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37941798-534a-4b45-b04d-2c348aff9c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>459e431e-a9ab-49b9-b170-abef9cb59514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NamaPerusahaan</value>
      <webElementGuid>4f4c2029-dc52-4478-b466-69e924b569e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NamaPerusahaan</value>
      <webElementGuid>fd2de4de-ae9b-42fa-a87b-14b9279ca356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>c514e953-883a-4958-909a-d5aba00ae35b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input</value>
      <webElementGuid>70ceb460-00af-4812-b8c1-bef9ae9bc84c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>190d6e38-d65f-4a1a-adf4-0fa2f84b3363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>1417f54a-7d6e-4f82-8172-3b2906aa6dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>9c665772-56a5-41fa-bdf6-0730e5e01ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>193b7a71-6901-46e6-bcf3-4ba83282963f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NamaPerusahaan&quot;)</value>
      <webElementGuid>e2aa4c31-45ca-460e-a078-5772ed3f0386</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NamaPerusahaan']</value>
      <webElementGuid>06db2b08-bb9d-416b-b8dd-ee4ef5278651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='_tr_JenisPasien']/td[2]/table/tbody/tr[2]/td[2]/input[2]</value>
      <webElementGuid>5a85d2a4-dce0-4999-b120-1a0ba69f1643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[11]/td[2]/table/tbody/tr[2]/td[2]/input[2]</value>
      <webElementGuid>8942af28-5207-4a69-8259-9aecb67a0dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'NamaPerusahaan' and @name = 'NamaPerusahaan']</value>
      <webElementGuid>9f606cb0-3276-41e5-8b27-cf321c6ab58a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
