<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No.Induk KependudukanKTP_nik_nya</name>
   <tag></tag>
   <elementGuidId>5b66c27a-2f62-4fdf-a68b-9b7c981f247b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nik_nya</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nik_nya']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#nik_nya</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c7ca54a-3c88-4112-ba0b-3980dd381a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cd02774e-6c45-4e07-ac51-ed2f46a681bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nik_nya</value>
      <webElementGuid>01f8d477-16b3-41e5-8e0e-e0c009697025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nik_nya</value>
      <webElementGuid>9f0a3728-7fbe-4876-837a-fa89a5d6c31b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>periksavalidasiangka(this,'numbers')</value>
      <webElementGuid>9b69f864-04a1-42f3-b890-49b76e7f647c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>6d6631a6-b076-4be3-8ff9-a34684036722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nik_nya&quot;)</value>
      <webElementGuid>43255a21-e572-47ce-8047-1578dbdbea7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nik_nya']</value>
      <webElementGuid>c0837f5c-f6ad-4de6-a12e-8ac8d44af6fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='_span_nik']/input</value>
      <webElementGuid>d8032988-0511-4f37-b64b-8d85efad1be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[2]/span/input</value>
      <webElementGuid>98d628db-04e3-4c5b-82d1-cf9be7fb00d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nik_nya' and @name = 'nik_nya']</value>
      <webElementGuid>b5cc1b7d-4333-482f-adcc-3f2c85475961</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
