<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No. Polis  No. Kartu_NomerPolis</name>
   <tag></tag>
   <elementGuidId>660c7b8c-b1c9-45de-bfd3-0b9ddbf0d8aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NomerPolis</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NomerPolis']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#NomerPolis</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>128548c9-b0db-4c43-a069-e5ddf6fb582a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c8fa5b28-7dfd-4c33-b018-3102eda7a522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NomerPolis</value>
      <webElementGuid>52077408-1acd-47d5-a9d5-fc10c044d7d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NomerPolis</value>
      <webElementGuid>7eace7e7-d201-4bae-aa0f-516549c6e1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>e8a30a34-f15a-4077-af92-b13a316eee32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>periksavalidasiangka(this,'alphanum')</value>
      <webElementGuid>daa7fae1-552d-4c01-90a7-095572b360b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NomerPolis&quot;)</value>
      <webElementGuid>af2a4f4a-35de-48df-b468-ab353bbec920</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NomerPolis']</value>
      <webElementGuid>739381e8-7300-45c8-8ee3-e9fd38a7856b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='_tr_JenisPasien']/td[2]/table/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>e370326c-2f30-4223-bff8-1282e9215e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>eb2cbe0c-406f-4705-b18b-aa6c5bbdf129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'NomerPolis' and @name = 'NomerPolis']</value>
      <webElementGuid>78926646-2ef4-4465-87cf-3b92957510bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
