<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Untuk pasien BPJS, isi dengan Nomor R_71e493</name>
   <tag></tag>
   <elementGuidId>a1c22629-8272-4db1-b597-7cce808d67d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#InputJKNNoRujukan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='InputJKNNoRujukan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#InputJKNNoRujukan</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ab1b8a7-50e8-48c9-9b3e-83a7b5cce67f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5b215ce0-918d-4138-9e2d-ea76b1dc6eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InputJKNNoRujukan</value>
      <webElementGuid>c3d726f9-03ea-4492-ac92-5cc7573a3231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>JKNNoRujukan</value>
      <webElementGuid>19a4c8c7-4fb7-4c56-bb57-2adbc41316d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>44adc5c7-3ccc-44aa-926e-eed7216abac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InputJKNNoRujukan&quot;)</value>
      <webElementGuid>489fdf2d-bcb2-478a-93e0-6809661cb1eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='InputJKNNoRujukan']</value>
      <webElementGuid>c3bad7aa-5d68-4e58-8fb2-614d93a4a3ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='_tr_JenisPasien']/td[2]/table/tbody/tr[10]/td[2]/input</value>
      <webElementGuid>76d26276-6bbe-4427-b16b-fd7cba3063ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[2]/input</value>
      <webElementGuid>023f61f1-4205-4043-b24a-30c0ada5c580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'InputJKNNoRujukan' and @name = 'JKNNoRujukan']</value>
      <webElementGuid>666aeaa1-b050-478a-9ed7-ada9570f63bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
