<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cari Pasien__btn_pendaftaran_rj</name>
   <tag></tag>
   <elementGuidId>fd7dc6b7-09bc-4a1b-980f-57a667c8ccfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_btn_pendaftaran_rj</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_btn_pendaftaran_rj']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Pendaftaran RJ (F1)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0350e22d-d15e-4eb4-af5b-87cc8a29ef5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6f1b484b-321f-42fd-be26-77b80b4ef89b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_btn_pendaftaran_rj</value>
      <webElementGuid>640028c1-ee68-4406-bdd5-10b59f3de588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_btn_pendaftaran_rj</value>
      <webElementGuid>3b7d9581-00dc-487c-99e7-921ec047ae77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Pendaftaran RJ (F1)</value>
      <webElementGuid>39bd394a-987f-4e70-9d78-ee8bd5101826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>fn_pendaftaran('rj')</value>
      <webElementGuid>b8933042-6c1b-4fe5-b800-030402b03801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button ui-widget ui-state-default ui-corner-right ui-state-hover ui-state-focus</value>
      <webElementGuid>a84eccec-3a9d-44f7-809b-f5275da5d81c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>372409f5-bfca-4536-aac1-4ad9e3f36638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fb40b3f0-786d-45f8-8d1b-d0cd67ff1959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_btn_pendaftaran_rj&quot;)</value>
      <webElementGuid>2aab2350-6113-43a0-ab35-cb7f28bcf79d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_btn_pendaftaran_rj']</value>
      <webElementGuid>1d520536-5af3-4bd9-b5d8-57eedc8b1a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_div_btn_rj']/input[3]</value>
      <webElementGuid>22d4d881-55e5-40ce-b550-a59de8d3e2dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[3]</value>
      <webElementGuid>cd10a7c6-fcd4-4c3a-b2ef-24fa28960f0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = '_btn_pendaftaran_rj' and @name = '_btn_pendaftaran_rj']</value>
      <webElementGuid>b0c430f7-48bb-4d34-827d-710deded5b50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
