<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Keterangan__btn_info_vaksin</name>
   <tag></tag>
   <elementGuidId>d1d126ed-6d4c-4a02-b28b-007376af11cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_btn_info_vaksin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_btn_info_vaksin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Informasi Vaksin&quot;i >> internal:role=button[name=&quot;Simpan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd7317e9-b18f-4903-9ac9-ffbb59ecc248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cec7e428-5637-4b31-ada8-597346eca397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_btn_info_vaksin</value>
      <webElementGuid>a46c3e9b-b578-479c-bbae-ba7696365f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_btn_info_vaksin</value>
      <webElementGuid>d431226b-88e2-4579-bf1e-778184f42a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>8c5f63b0-97c5-45f4-aa84-83f72e49e55e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>SimpanVaksin()</value>
      <webElementGuid>698aa734-a2b2-4fa3-8911-a68cc0605e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>ae13bcfe-5b5f-4de0-8cb6-b42268496372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3b7a9ce0-544c-403c-abb8-676ceac90411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ec7971c2-2ddd-42e5-80d3-3c017be98853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_btn_info_vaksin&quot;)</value>
      <webElementGuid>a9fa94ea-f713-49ee-bc61-0037c06c9e8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_btn_info_vaksin']</value>
      <webElementGuid>c4d09276-9ea9-444d-9689-a8a6a7a66d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//span[@id='Email_Pengiriman']/input)[2]</value>
      <webElementGuid>3e2fcfb7-aa33-4f46-ae01-a0cf7870eb20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/span/input</value>
      <webElementGuid>2adb3db9-c37b-420f-bd74-22b8f8443388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = '_btn_info_vaksin' and @name = '_btn_info_vaksin']</value>
      <webElementGuid>fa940870-6ace-4a65-b4a4-4d2717057bf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
