<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dokter__btn_tambahkan_poli</name>
   <tag></tag>
   <elementGuidId>61a95822-4ab8-4a18-83c7-57a3387cc8fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_btn_tambahkan_poli</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_btn_tambahkan_poli']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Tambahkan&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c96bcdca-583a-4dad-9194-040d691684ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c04776a0-4108-4668-8372-145435c2ca15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_btn_tambahkan_poli</value>
      <webElementGuid>54ae7b2f-fd17-4aef-8bea-02e3a7b60d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_btn_tambahkan_poli</value>
      <webElementGuid>bad31f1c-1b45-4c5c-9831-8000558f83ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Tambahkan</value>
      <webElementGuid>6b78e9b6-aea3-4105-bfba-dabc84c43cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>fn_tambahkan_poli()</value>
      <webElementGuid>23d17ccc-be1c-4e72-998a-0f88478ce32c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_btn_tambahkan_poli&quot;)</value>
      <webElementGuid>b1f41cc2-fffe-4aa3-ab25-467436e8cf06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_btn_tambahkan_poli']</value>
      <webElementGuid>3144eb3d-4bab-4aab-b04c-248cf53efa58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='_tr_poli_dept']/td/input[6]</value>
      <webElementGuid>926df9d8-bf3f-410d-9170-0aff5c89787d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input[6]</value>
      <webElementGuid>da07169c-652d-40b4-a73c-f1e55567f4e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = '_btn_tambahkan_poli' and @name = '_btn_tambahkan_poli']</value>
      <webElementGuid>69b77eb7-ec84-4b6f-ad2c-55563f1c8ea9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
