<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cari Rek.Med_cari_mrid</name>
   <tag></tag>
   <elementGuidId>e4f62e29-9f36-44a3-a6e9-cc9139d280a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cari_mrid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cari_mrid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cari_mrid</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee633288-b169-47a4-932c-a25d13bbd92a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84499df5-3066-40bd-abd1-79d4ad96aaac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cari_mrid</value>
      <webElementGuid>576bde93-f716-40f2-b37d-2264b8ca3c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cari_mrid</value>
      <webElementGuid>478895d6-f3be-4d8b-b8e7-d6f1b99ba0ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>7ded830b-82fa-4336-bfcb-20cd75096ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cari_mrid&quot;)</value>
      <webElementGuid>7513e70f-1c4b-419c-9422-0302414c368f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cari_mrid']</value>
      <webElementGuid>8317d478-0489-4c72-9d2f-c9a50c7535d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_div_pencarian_mr']/input</value>
      <webElementGuid>9600ac66-a879-49f5-a3bc-f14b530b2a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div[2]/div/input</value>
      <webElementGuid>01025ca2-d557-4c86-97b1-38cdb243e0a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'cari_mrid' and @name = 'cari_mrid']</value>
      <webElementGuid>0f127041-94a3-438e-bd7d-05c6878a56bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
