<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cari Tanggal Lahir__btn_pencarian_mr</name>
   <tag></tag>
   <elementGuidId>51059815-f252-4524-b2df-f03498bc7575</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_btn_pencarian_mr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_btn_pencarian_mr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;_btn_pencarian_mr&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0c49869e-561d-4a16-95ea-41fa0ea16721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5537086e-cb7e-414c-be7b-a88045f0a6d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_btn_pencarian_mr</value>
      <webElementGuid>f273476b-75df-458c-95aa-5bcd43575603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_btn_pencarian_mr</value>
      <webElementGuid>7e21a5f4-3d87-4b96-b79e-c6441eefddc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Cari</value>
      <webElementGuid>78ca5b65-791a-4b0a-85a4-bbc25f92faf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>fn_cari_mr_daftar()</value>
      <webElementGuid>7c1f1750-f5b7-4d94-aa72-d7c858b4ad34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>4440b121-64af-43f4-b14f-f54503c1f984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>95e19c14-919d-4f29-9539-6e8aad78200b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8b1851ee-42ec-4830-9d38-9a9e1d160003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_btn_pencarian_mr&quot;)</value>
      <webElementGuid>f2f5cad6-ea9d-485c-844d-b33b5ae57e1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_btn_pencarian_mr']</value>
      <webElementGuid>02f05e16-c765-481b-91e8-1c8de3900ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_div_pencarian_mr']/input[6]</value>
      <webElementGuid>5e743cd9-62ec-44de-a43e-4191d662611a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input[6]</value>
      <webElementGuid>a1efbb9b-bfdc-4fdf-a2ac-1814135a9cff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = '_btn_pencarian_mr' and @name = '_btn_pencarian_mr']</value>
      <webElementGuid>9893264a-378e-4725-9630-f609bca6f4f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
