<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Untuk pasien BPJS, isi dengan Nomor S_a4af4a</name>
   <tag></tag>
   <elementGuidId>71c6ab98-f3ef-4967-a6d7-8bd267036f7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NomerJaminan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NomerJaminan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#NomerJaminan</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3241933d-1702-46c2-827e-59b643fbaf55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7b616758-e2df-4bdd-846e-5bb7b9495f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NomerJaminan</value>
      <webElementGuid>14af1e35-7c53-4f90-a714-f2f4eb4dce83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NomerJaminan</value>
      <webElementGuid>2927a6eb-34f7-42e0-8cbe-e7a161642814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>cb241d6a-b156-4eaa-9f57-9eafde5c7836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>periksavalidasiangka(this,'alphanum')</value>
      <webElementGuid>b59553c5-dc4c-4349-a849-f5016da7d63c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NomerJaminan&quot;)</value>
      <webElementGuid>28c1941f-f177-47f4-b1c4-182172fa17f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NomerJaminan']</value>
      <webElementGuid>4cc381a3-0025-49d9-a42b-5488941d2383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='_tr_JenisPasien']/td[2]/table/tbody/tr[8]/td[2]/input</value>
      <webElementGuid>9d00e495-6e84-4cbc-b830-1bac796974cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr[8]/td[2]/input</value>
      <webElementGuid>9d07fc26-f972-4e13-892c-4ba9d7fbbae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'NomerJaminan' and @name = 'NomerJaminan']</value>
      <webElementGuid>1779cacc-970c-4d95-b62e-35e60a4e0141</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
