<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NA_btnpilih</name>
   <tag></tag>
   <elementGuidId>1f5bbf2c-9a39-4993-823a-27623aceded4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tr_94 > td > p > span > #btnpilih</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='btnpilih'])[13]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Pilih 94 14:45&quot;i] >> #btnpilih</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec7fb856-111b-461b-b378-a4aa4a9129c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>772b7753-0b50-48cc-82d6-2fb768aa762f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnpilih</value>
      <webElementGuid>c3882674-25a2-456c-aa23-fff7c50b6673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnpilih</value>
      <webElementGuid>ab58ce6c-f745-4937-99ba-25170025ad36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn blue</value>
      <webElementGuid>0c1e9b8a-8bdf-45fa-8cbc-af4491c3af03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Pilih</value>
      <webElementGuid>49f40209-0627-430d-9a60-139050612218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>fn_pilihslot('AUTO','00409245','MED-POLI-INTERNIS','DRFAD','1296','560989','2024-10-16','94','N')</value>
      <webElementGuid>13f539f1-f73f-49ca-ab6c-fb3f4f6c54de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tr_94&quot;)/td[1]/p[1]/span[1]/input[@id=&quot;btnpilih&quot;]</value>
      <webElementGuid>7f558acb-6390-4948-96a5-60b6101bd98b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='btnpilih'])[13]</value>
      <webElementGuid>2d7fef8e-a81c-487b-a7f3-f3886d8b28bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr_94']/td/p/span/input</value>
      <webElementGuid>e403c504-a36c-40b9-9d86-cfd0d17387f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[94]/td/p/span/input</value>
      <webElementGuid>0bfee7b1-ad5d-4a1c-922c-66522c0ad366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnpilih' and @name = 'btnpilih']</value>
      <webElementGuid>7d11d9e4-fa9c-498e-83d1-2e493eedb294</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
