<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Diisi jika yg berobat keluarga karyaw_c87913</name>
   <tag></tag>
   <elementGuidId>6cd2f490-9705-46b5-a69a-890026a7132a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NamaKaryawan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NamaKaryawan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#NamaKaryawan</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29129396-d585-43d8-92bb-cff11e59f08d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>073c7470-498e-4cf6-bea3-00aa3606314a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NamaKaryawan</value>
      <webElementGuid>cdde2b58-ff1a-493b-934d-7708dd4c90be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NamaKaryawan</value>
      <webElementGuid>0e2f22b2-f837-4eda-9a70-cec12f0a3295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>019a89ed-63f5-4823-8807-b99e8ec5d67f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NamaKaryawan&quot;)</value>
      <webElementGuid>4b0aa9bb-2480-44c3-a68f-d12e860274f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NamaKaryawan']</value>
      <webElementGuid>b2ba681d-0de7-40ea-886f-85fe8d355a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='_tr_JenisPasien']/td[2]/table/tbody/tr[7]/td[2]/input</value>
      <webElementGuid>2d942c2e-5f67-40c4-b6f7-2098bb827192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr[7]/td[2]/input</value>
      <webElementGuid>1a4d4b69-6118-473f-84d0-ebcfe69a3dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'NamaKaryawan' and @name = 'NamaKaryawan']</value>
      <webElementGuid>77980d25-01dc-4c19-b23e-c477cf8d8c6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
