<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DeptPoli_NamaDepartemen</name>
   <tag></tag>
   <elementGuidId>11492c7a-adfe-4346-8344-03bff3377fcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NamaDepartemen</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NamaDepartemen']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#NamaDepartemen</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>01fbaf2b-478d-4589-aede-67543841c14e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>61e8bfb4-df4e-4a53-ae4e-1cf96bf7009d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NamaDepartemen</value>
      <webElementGuid>a3d666b3-b2e1-4654-96b0-695759bef2f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NamaDepartemen</value>
      <webElementGuid>a7d69378-e1b1-4da3-96cb-ebe663d90e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>53efc0ad-ba60-4723-9cec-355245893972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>cek(this.value, '#DepartemenID', '#_frm_pendaftaran_rj');</value>
      <webElementGuid>4450ad17-7250-4dcd-a623-d341be3c6084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input</value>
      <webElementGuid>855b0e14-0538-45a8-bad6-66bcd87bd773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8e974b39-442b-4852-89a3-4f3e75d92843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>24cbb4b1-f4ff-4d96-814b-1cb7d3ae379c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>c4aed3ff-a811-4efe-b8c2-b6bf491c3a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>58e53df9-1f7d-44e0-9d92-ac13831fe7c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NamaDepartemen&quot;)</value>
      <webElementGuid>f761e70e-4d3e-4aa7-b9db-588cd8c3c2a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NamaDepartemen']</value>
      <webElementGuid>01cb8a95-93d9-48ad-b9a3-ca338c5de09f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='_tr_poli_dept']/td/input[3]</value>
      <webElementGuid>c93d4464-5dab-4321-9b90-7dfe0314a73d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[18]/td/input[3]</value>
      <webElementGuid>4cc88de5-9109-45f2-82e8-11d1ebae11a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'NamaDepartemen' and @name = 'NamaDepartemen']</value>
      <webElementGuid>90a49e00-15c9-427c-af18-8fdd6d88f555</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
