<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_UmumJaminan PerusahaanJaminan Asuransi</name>
   <tag></tag>
   <elementGuidId>97af536b-3931-4e59-bcbe-73cbf7a31fdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#JenisPasienID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='JenisPasienID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#JenisPasienID</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0a188a9c-d164-429d-bc63-2fe2731f934f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>JenisPasienID</value>
      <webElementGuid>c1603f91-829c-4eb2-92a9-0570fd7f7dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>JenisPasienID</value>
      <webElementGuid>a723e5cc-98a3-4038-982a-1f7587174f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>cek_JenisPasien()</value>
      <webElementGuid>5fe655c1-7ffd-4647-8ecd-d5207f1c87d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UmumJaminan PerusahaanJaminan Asuransi</value>
      <webElementGuid>08f3f642-b667-4493-a9a7-607e543d46e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;JenisPasienID&quot;)</value>
      <webElementGuid>82eec215-2249-4da0-a575-3edc86bc55b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='JenisPasienID']</value>
      <webElementGuid>e651ca96-cc35-468e-a2a9-72de1c142b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='_frm_pendaftaran_rj']/table/tbody/tr[9]/td[2]/select</value>
      <webElementGuid>8dc4abf8-9752-48f6-af54-488acddcb094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Pasien:'])[1]/following::select[1]</value>
      <webElementGuid>51974c46-50e8-4f5f-a67f-b406b8cc375c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*KHUSUS PASIEN BPJS WAJIB DI ISI.'])[1]/following::select[1]</value>
      <webElementGuid>038dfe5e-8646-41d6-aaff-ec55374ffad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TeleConsultation'])[1]/preceding::select[1]</value>
      <webElementGuid>194eee98-dfa1-47fa-b657-caceff3bdb44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Periode Tarif :'])[1]/preceding::select[1]</value>
      <webElementGuid>b8a19abf-b644-4561-ab2f-3a77a167d208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[2]/select</value>
      <webElementGuid>e3e39f16-6cd9-4e6a-ba9e-6769f7e10815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'JenisPasienID' and @name = 'JenisPasienID' and (text() = 'UmumJaminan PerusahaanJaminan Asuransi' or . = 'UmumJaminan PerusahaanJaminan Asuransi')]</value>
      <webElementGuid>4829ef04-f69f-4db6-aefb-000f77a998bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
