<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cari Pasien__btn_pendaftaran_rj</name>
   <tag></tag>
   <elementGuidId>e3c376b6-1178-4e61-a700-0de648763327</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_btn_pendaftaran_rj']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_btn_pendaftaran_rj</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Pendaftaran RJ (F1)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a63b9309-27cb-45f9-a4f3-6916ce9c3d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8f42cd29-2ce5-4964-9777-e429bd1e8783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_btn_pendaftaran_rj</value>
      <webElementGuid>a9528164-f369-480f-b085-603aa8b216b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_btn_pendaftaran_rj</value>
      <webElementGuid>f4c4a66d-5f79-4c1e-bfda-96bf59ca6a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Pendaftaran RJ (F1)</value>
      <webElementGuid>4e91a8bc-acc9-49e7-aac4-4c2ada109b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>fn_pendaftaran('rj')</value>
      <webElementGuid>ff77559e-2b96-4a6b-9ed0-3d11d0a7b4f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button ui-widget ui-state-default ui-corner-right ui-state-hover ui-state-focus</value>
      <webElementGuid>73003c1d-e379-4e8c-b1a1-2f0324baf324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cb31dd42-fe8b-468c-85ab-26527d76a08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>98e7ec1d-402b-44aa-a4c7-e0f1ec180a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_btn_pendaftaran_rj&quot;)</value>
      <webElementGuid>decf09a9-bbdb-4135-966d-070bf32f59ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_btn_pendaftaran_rj']</value>
      <webElementGuid>2ad95a44-619b-4ff7-932c-b9d0a238241c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_div_btn_rj']/input[3]</value>
      <webElementGuid>ba95c830-cfb1-40d5-b983-b86b6372df32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[3]</value>
      <webElementGuid>ba50bc25-58eb-4045-b38b-b645fd1fd6d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = '_btn_pendaftaran_rj' and @name = '_btn_pendaftaran_rj']</value>
      <webElementGuid>d1efcb49-a15c-49b2-bbf0-4338f05a520f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
