<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Rawat Jalan</name>
   <tag></tag>
   <elementGuidId>f631bf80-e93d-4b38-977e-9f9a33794c1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='_GroupShiftID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_GroupShiftID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;_GroupShiftID&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7adafe25-db99-474e-9e39-54f5d61fcf94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_GroupShiftID</value>
      <webElementGuid>5f180963-d6b3-4af3-b906-bc3c4eede58c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_GroupShiftID</value>
      <webElementGuid>39a429ed-1198-4558-b909-87ec9cf77127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Rawat Jalan
</value>
      <webElementGuid>165ceada-192f-4bca-ba6f-ccf8969b6437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_GroupShiftID&quot;)</value>
      <webElementGuid>f5a1f19a-6c49-44ee-9c7b-b838f71b1015</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='_GroupShiftID']</value>
      <webElementGuid>e9b475bf-363d-48b4-ab7c-610ae59322ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='openshift']/table/tbody/tr/td[2]/select</value>
      <webElementGuid>ff2d7872-ff57-4145-b406-5f52ebf455dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jika ingin membuka shift baru, silakan isi form di bawah ini.'])[1]/following::select[1]</value>
      <webElementGuid>f96f5266-9000-47d2-bea4-282cd6f808b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/table/tbody/tr/td[2]/select</value>
      <webElementGuid>87156b36-e890-46dc-a926-f69333497421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '_GroupShiftID' and @name = '_GroupShiftID' and (text() = '
Rawat Jalan
' or . = '
Rawat Jalan
')]</value>
      <webElementGuid>f5f74516-b73f-49cb-947e-b3a423435faf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
