<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dr.Ahmad Fadhil</name>
   <tag></tag>
   <elementGuidId>af911254-b223-49e3-ae68-f0ed56a5299a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ui-active-menuitem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-active-menuitem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Dr.Ahmad Fadhil&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d2da970d-d260-4f99-a107-b8beed2040a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-corner-all ui-state-hover</value>
      <webElementGuid>c9b5ff2d-b67e-4c79-a229-ff702a380d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5915ade8-f877-4b49-b945-c5933444071e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-active-menuitem</value>
      <webElementGuid>7a67f6db-3b55-4db3-a998-91d6d30049c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dr.Ahmad Fadhil</value>
      <webElementGuid>24ed85f6-ede8-4a84-8a9d-64aeedbfd4b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-active-menuitem&quot;)</value>
      <webElementGuid>676cf72b-f023-4078-a1ff-2b091e07d213</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ui-active-menuitem']</value>
      <webElementGuid>ff4fddf7-1652-4518-9a0d-0365f999fc2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Dr.Ahmad Fadhil')]</value>
      <webElementGuid>208d5d79-b33f-4659-82a5-0613d40ac4c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POLI PENYAKIT DALAM BPJS'])[2]/following::a[1]</value>
      <webElementGuid>3639fce3-9803-4144-8df1-2b30d4dfc4e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POLI PENYAKIT DALAM'])[2]/following::a[2]</value>
      <webElementGuid>16fed1a2-1551-4174-8f7d-fa82b5a831ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='close'])[27]/preceding::a[1]</value>
      <webElementGuid>4033d40c-f40e-4432-b773-cd2b707363bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BRIDGING INHEALTH'])[1]/preceding::a[2]</value>
      <webElementGuid>2ec69760-eac6-4f77-8d30-2bb9f0d40b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dr.Ahmad Fadhil']/parent::*</value>
      <webElementGuid>32d089cf-5bc8-4d6d-b245-7e1af8a9900b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[3]/li/a</value>
      <webElementGuid>7b0dc929-c3a1-4195-b1bd-40d229f4309c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ui-active-menuitem' and (text() = 'Dr.Ahmad Fadhil' or . = 'Dr.Ahmad Fadhil')]</value>
      <webElementGuid>805af1db-ac05-4522-923b-ceb65aec8edb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
