<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_POLI PENYAKIT DALAM</name>
   <tag></tag>
   <elementGuidId>fd66da06-80e9-43bd-8e73-dbc0be350d4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ui-active-menuitem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-active-menuitem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ui-active-menuitem</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5ae22b01-b4a7-491b-aef4-bcfeeb1782b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-corner-all ui-state-hover</value>
      <webElementGuid>4153a8d4-8df5-41ef-88c8-4c813325a5b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b7502125-e2b3-49dc-a1fd-83383e2c0814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-active-menuitem</value>
      <webElementGuid>e8712374-1706-488f-b0d5-50cbbe474d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>POLI PENYAKIT DALAM</value>
      <webElementGuid>4cff003e-fbf6-44a7-93a0-828c2929c89e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-active-menuitem&quot;)</value>
      <webElementGuid>4936d494-0ef7-4d10-acfb-bf8995a04dbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ui-active-menuitem']</value>
      <webElementGuid>6f250271-bbf0-4bfe-baf6-888a9c049e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'POLI PENYAKIT DALAM')]</value>
      <webElementGuid>42db04f9-5996-4847-b5a1-e3c4d9a872f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[2]/following::a[1]</value>
      <webElementGuid>47b08057-7e2a-431e-94ed-078260efb3a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[7]/following::a[1]</value>
      <webElementGuid>ddcd74f6-e75f-4ead-9356-31744b45e513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POLI PENYAKIT DALAM BPJS'])[2]/preceding::a[1]</value>
      <webElementGuid>48aab99c-b6c4-4d99-93d5-131df8406eaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='close'])[27]/preceding::a[2]</value>
      <webElementGuid>6ec31cd9-4afd-4100-b1a4-06c9acb7fcef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li/a</value>
      <webElementGuid>996638eb-3ad9-40dd-a853-26698cbc2d2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ui-active-menuitem' and (text() = 'POLI PENYAKIT DALAM' or . = 'POLI PENYAKIT DALAM')]</value>
      <webElementGuid>ddad0999-7b34-48e2-b664-75a03c4c4cbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
