<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>font_harus diisi</name>
   <tag></tag>
   <elementGuidId>ba10f82f-1a1d-4291-ac99-06f68110b22e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='_frm_mr_baru']/table/tbody/tr[14]/td[2]/span/font</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(14) > td:nth-of-type(2) > span.ui-harus > font</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Status Perkawinan: • harus diisi&quot;i] >> font</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>e1a10c3a-fd75-4795-8f84-8e2a65f685ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>maroon</value>
      <webElementGuid>60e6184a-6090-4138-96eb-409634018feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>• harus diisi</value>
      <webElementGuid>f6d42ace-38cc-485c-a78e-fc25a9a39a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_frm_mr_baru&quot;)/table[@class=&quot;tabel&quot;]/tbody[1]/tr[14]/td[2]/span[@class=&quot;ui-harus&quot;]/font[1]</value>
      <webElementGuid>fa0a89e2-6d9a-476a-96ef-1daa7c933e19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='_frm_mr_baru']/table/tbody/tr[14]/td[2]/span/font</value>
      <webElementGuid>db978d7e-17fb-471a-8582-6247b9114f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Perkawinan:'])[1]/following::font[1]</value>
      <webElementGuid>2d4c1881-15bb-408a-b2ee-7cffb840cacb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='• harus diisi'])[7]/following::font[1]</value>
      <webElementGuid>4866a0b5-e229-45f3-b2b5-c13fa199fbb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomer Identitas:'])[1]/preceding::font[1]</value>
      <webElementGuid>3f4ce79a-f670-451e-b695-087b98788dd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='• harus diisi'])[9]/preceding::font[1]</value>
      <webElementGuid>13d91d2b-2593-4703-9bad-c81548c8045c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[14]/td[2]/span/font</value>
      <webElementGuid>7903c71e-0473-4d46-877c-a6f591c0d54f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//font[(text() = '• harus diisi' or . = '• harus diisi')]</value>
      <webElementGuid>681fb6d7-fb65-4274-bc1a-9abf48c8c8b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
