<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Pasien_Nama</name>
   <tag></tag>
   <elementGuidId>4829c8bd-bc6e-4ad0-b46d-aab65ba9737f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Nama']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Nama</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Rekam Medis&quot;s >> #Nama</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb04725f-2b11-4483-8fb6-8073312bd1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9cb9fd47-f79f-4600-90cb-ba5f3168550e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Nama</value>
      <webElementGuid>331a2881-ee91-4d7e-babe-723f731e0feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Nama</value>
      <webElementGuid>f469ea63-cd79-4616-820d-87b92204c9ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>21c1a489-90dd-4c1f-a90a-ee5f03ee64d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_frm_mr_baru&quot;)/table[@class=&quot;tabel&quot;]/tbody[1]/tr[2]/td[2]/input[@id=&quot;Nama&quot;]</value>
      <webElementGuid>f8305222-6abc-4338-9bfc-24483dfe311d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Nama']</value>
      <webElementGuid>a8309a4c-9c38-4797-b217-20603bdce0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='_frm_mr_baru']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>39321fb2-ff6b-4b95-b9ba-699222f63202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>d65475b0-0fd0-454b-b1d4-cb0e6bc5ee10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Nama' and @name = 'Nama']</value>
      <webElementGuid>3f74cb59-0cde-45a8-969d-1602def2c599</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
