<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomer Identitas_NomerSosial</name>
   <tag></tag>
   <elementGuidId>606068c6-7a00-43ac-b5d5-1764f20350fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NomerSosial']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NomerSosial</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Rekam Medis&quot;s >> #NomerSosial</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>465d064f-5b40-421e-ac44-c8fbcd0cc8bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>88b33733-da46-4d51-a98c-5e32c28c95c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NomerSosial</value>
      <webElementGuid>f21b4c02-b409-4428-8a75-7cd8e1d2fea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NomerSosial</value>
      <webElementGuid>b38fb536-e75b-4afa-a9df-70087a8d990d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>periksavalidasinik(this,'JenisNomerSosial','_frm_mr_baru')</value>
      <webElementGuid>a6f45eb2-5026-4648-9237-a9c031bbca1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>3ac503b5-6633-4356-a9c1-7404a4979c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_frm_mr_baru&quot;)/table[@class=&quot;tabel&quot;]/tbody[1]/tr[15]/td[2]/input[@id=&quot;NomerSosial&quot;]</value>
      <webElementGuid>d952e94a-1444-4978-bc80-4aeef14447d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NomerSosial']</value>
      <webElementGuid>de4b5e7f-a83f-4977-931f-5cf936cb4bf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='_frm_mr_baru']/table/tbody/tr[15]/td[2]/input</value>
      <webElementGuid>e30f33f5-29a1-425a-b5fb-62e66b871db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/table/tbody/tr[15]/td[2]/input</value>
      <webElementGuid>58dc6ac6-b795-497b-9a41-4d4c8b736a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'NomerSosial' and @name = 'NomerSosial']</value>
      <webElementGuid>65cc095c-7ade-4051-9fec-ee3235e6bf3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
