<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cari Pasien__btn_pendaftaran_rj</name>
   <tag></tag>
   <elementGuidId>9d527427-eaa8-4c3a-b703-dba52f859c3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_btn_pendaftaran_rj']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_btn_pendaftaran_rj</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Pendaftaran RJ (F1)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ada17f03-1d6a-4621-8bc3-6f35fcf8d119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ac13960e-0fa7-443c-96d9-b014676e3d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_btn_pendaftaran_rj</value>
      <webElementGuid>a5a7c4c4-8ca4-429d-93b0-442f3b3b2034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_btn_pendaftaran_rj</value>
      <webElementGuid>f6c1df74-726c-48a8-853c-f85669e564f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Pendaftaran RJ (F1)</value>
      <webElementGuid>a1d39a73-7034-49b8-8b9e-18aa60c52a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>fn_pendaftaran('rj')</value>
      <webElementGuid>979c92fe-a38d-47f2-82b1-7146b2c5d57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button ui-widget ui-state-default ui-corner-right ui-state-hover ui-state-focus</value>
      <webElementGuid>3444ae9d-c335-4c70-b6f1-6c5260d0959c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bdf47b55-f441-4e42-85d7-6c5ac15c40d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b4b92fd4-9008-494f-9c79-0bcfbedf39f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_btn_pendaftaran_rj&quot;)</value>
      <webElementGuid>1dfe90eb-ecfa-4ab7-88a5-8dbb48663cc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_btn_pendaftaran_rj']</value>
      <webElementGuid>ef45e739-25d6-47f8-899d-b437d4a0ff37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_div_btn_rj']/input[3]</value>
      <webElementGuid>ec7a3fa8-ffbb-42c0-845c-6df6c9e61a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[3]</value>
      <webElementGuid>437d08bc-894b-4edf-808f-899fe9550d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = '_btn_pendaftaran_rj' and @name = '_btn_pendaftaran_rj']</value>
      <webElementGuid>44f30520-2858-4d8a-b87b-575eb601cdf0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
