<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pekerjaan_Pekerjaan</name>
   <tag></tag>
   <elementGuidId>1603389e-ea00-4a29-baa8-05ae8857b8e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Pekerjaan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Pekerjaan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Rekam Medis&quot;s >> #Pekerjaan</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>405e80d0-1b9b-41c2-b2f6-f9a6f2f8d0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2b91cb75-5387-46e3-9a16-797ed48a04b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Pekerjaan</value>
      <webElementGuid>ef8d41d9-6451-4fb6-bb2d-b46f56e27b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Pekerjaan</value>
      <webElementGuid>2782a356-ca0d-470e-b9c2-af0cfd5022e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>f3062736-35ea-43d9-bf0b-59a9b9da287c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_frm_mr_baru&quot;)/table[@class=&quot;tabel&quot;]/tbody[1]/tr[8]/td[2]/input[@id=&quot;Pekerjaan&quot;]</value>
      <webElementGuid>f5098f03-c951-4dec-a961-0996247b966c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Pekerjaan']</value>
      <webElementGuid>f717aa15-5933-49cb-8218-9e7e47b5cd65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='_frm_mr_baru']/table/tbody/tr[8]/td[2]/input</value>
      <webElementGuid>b9eee2af-a2d0-40bb-9bb4-4dd860060562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/table/tbody/tr[8]/td[2]/input</value>
      <webElementGuid>081b2e45-b1ca-489e-a1cb-c3cfa8ecc128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Pekerjaan' and @name = 'Pekerjaan']</value>
      <webElementGuid>6c3dd427-5abb-4ff6-b243-8276b5c9d746</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
