<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ponsel_Ponsel</name>
   <tag></tag>
   <elementGuidId>ff6fc83e-f163-422b-ace4-05e228427188</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Ponsel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Ponsel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Rekam Medis&quot;s >> #Ponsel</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3feaf6ce-2b6d-4925-bae9-5ded7934f0cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ae61822f-1771-4e7a-a93c-0de7a494229d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Ponsel</value>
      <webElementGuid>7675c9e9-b959-4148-b625-8d791abbc370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Ponsel</value>
      <webElementGuid>b38438b5-fad6-458a-a426-fe732d9d9eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>01ef1d16-68c3-4029-a95c-131ee25a0566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_frm_mr_baru&quot;)/table[@class=&quot;tabel&quot;]/tbody[1]/tr[24]/td[2]/input[@id=&quot;Ponsel&quot;]</value>
      <webElementGuid>e724d625-c77f-4169-b93e-ee0888b39937</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Ponsel']</value>
      <webElementGuid>671eb4f5-875a-4568-ad2b-2c55e947541e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='_frm_mr_baru']/table/tbody/tr[24]/td[2]/input</value>
      <webElementGuid>6259e0f4-a2e6-4932-9251-470bcbf5475a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[24]/td[2]/input</value>
      <webElementGuid>d6b46fe9-d289-4f9e-9990-918bdc469c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Ponsel' and @name = 'Ponsel']</value>
      <webElementGuid>a797c85e-976c-4ef7-977b-4d98989718be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
