<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_format ddmmyyyy_TanggalLahirMR</name>
   <tag></tag>
   <elementGuidId>6f9689cb-6744-4879-969d-b14b7ad3350e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TanggalLahirMR']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TanggalLahirMR</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Rekam Medis&quot;s >> #TanggalLahirMR</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9eea1aea-3781-430a-a6c9-a2ef508117ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3a38d516-7d8b-49b5-8645-72d3e587f275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\d{4}-\d{1,2}-\d{1,2}</value>
      <webElementGuid>ec5ba5ed-586b-4372-8061-2c5a7d95990f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TanggalLahirMR</value>
      <webElementGuid>3df06263-296c-48ed-bbb9-3f36386162b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TanggalLahirMR</value>
      <webElementGuid>f4d85090-4628-4061-97f9-c472541748a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>15/</value>
      <webElementGuid>1a60a277-1cdc-436f-b5f9-9c5b61dd5739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hasDatepicker</value>
      <webElementGuid>1a5ac4b3-225d-4d73-b4a4-3f651e58933c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_frm_mr_baru&quot;)/table[@class=&quot;tabel&quot;]/tbody[1]/tr[13]/td[2]/input[@id=&quot;TanggalLahirMR&quot;]</value>
      <webElementGuid>1ef73304-9be0-4208-9514-7ca7d8f41791</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TanggalLahirMR']</value>
      <webElementGuid>fc631f82-1693-4ca8-a7b9-d86f200f7310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='_frm_mr_baru']/table/tbody/tr[13]/td[2]/input</value>
      <webElementGuid>57cfe294-aacd-4f63-9e69-1b05881ede3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/table/tbody/tr[13]/td[2]/input</value>
      <webElementGuid>73a8e0e0-59e0-4fca-bfa1-5b95f9aec63b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'TanggalLahirMR' and @name = 'TanggalLahirMR']</value>
      <webElementGuid>ead27a0c-e7b3-4f3a-a792-397a4e71170e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
