<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No. Rekam Medis__btn_medrec_baru</name>
   <tag></tag>
   <elementGuidId>9ad75c99-de42-47b8-9bac-9da9aa45fc26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_btn_medrec_baru']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_btn_medrec_baru</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Rek.Med. Baru (F2)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d067c15-b26b-477f-8706-ca0868341ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>96d78c38-42f9-4631-8ad9-283ff039c7b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Buat Rekam Medis Baru (Manual)</value>
      <webElementGuid>4c2f86b1-5fec-4fbd-89de-ac8ba17f6099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_btn_medrec_baru</value>
      <webElementGuid>4ca965ed-80e7-4fbd-8616-a85aeeb1a661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_btn_medrec_baru</value>
      <webElementGuid>d40c0321-4e43-4ba6-a8ea-da3ff9a809aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Rek.Med. Baru (F2)</value>
      <webElementGuid>953d6bb1-dd95-4a74-9750-6219e88cd4c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>fn_medrec_baru('rj')</value>
      <webElementGuid>318509b5-a0b8-463b-9a94-a03eb8a11819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button ui-widget ui-state-default ui-state-hover ui-state-focus</value>
      <webElementGuid>9cf45a31-4ba9-4a37-b499-1f7b1cf8ccfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>df196fbf-0037-4cc3-a6d9-8404d4c0adae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>83eb8cad-0c54-4664-a565-1f84f12c1171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_btn_medrec_baru&quot;)</value>
      <webElementGuid>43314bd2-bc6c-46a0-884b-a98a10c129d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_btn_medrec_baru']</value>
      <webElementGuid>1f84ee08-b129-4a6a-8590-6e32f2f4214c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='btn_med_']/input[2]</value>
      <webElementGuid>ae7346a3-0753-41ac-a1ac-790d41ac3a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/span/input[2]</value>
      <webElementGuid>6145f602-07c0-4904-bf9c-ded595bb8f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @title = 'Buat Rekam Medis Baru (Manual)' and @id = '_btn_medrec_baru' and @name = '_btn_medrec_baru']</value>
      <webElementGuid>784e66b1-c2a7-457c-8b58-b32092fb737b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
