<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_B O O K E D_btnpilih</name>
   <tag></tag>
   <elementGuidId>0bf0535e-553b-4ae9-9044-62eb90111e24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnpilih']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnpilih</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Pilih 7 23:05&quot;i] >> #btnpilih</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b53d654-b60f-445a-9712-9de3b8f366b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2ae43634-70f0-4ff7-9cf5-22780dc32d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnpilih</value>
      <webElementGuid>bf030dc3-0a49-4c58-8004-e79f86c76d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnpilih</value>
      <webElementGuid>e5111637-b0a3-408f-a87a-a083dfd0955a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn blue</value>
      <webElementGuid>6ce6a7f1-6f60-4b96-b2c0-413280168bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Pilih</value>
      <webElementGuid>e1af29a5-e67c-46a3-81b5-662df56f6802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>fn_pilihslot('AUTO','00409246','MED-POLI-INTERNIS','DRFAD','1297','563725','2024-10-17','7','N')</value>
      <webElementGuid>f0870185-07ae-44f2-964d-c4919afb754e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tr_7&quot;)/td[1]/p[1]/span[1]/input[@id=&quot;btnpilih&quot;]</value>
      <webElementGuid>eaf67652-b1f9-4e12-9f69-a98649c5ed2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnpilih']</value>
      <webElementGuid>7404afab-37f2-4d64-b9a8-98aa240681dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr_7']/td/p/span/input</value>
      <webElementGuid>90b40c45-1840-4c98-a677-b9fe90daa10c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/span/input</value>
      <webElementGuid>af4c753a-12e3-42cc-affa-5eddaad91d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnpilih' and @name = 'btnpilih']</value>
      <webElementGuid>328edf4d-7e7a-4db1-a3d8-7de2cbf3fee6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
