<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dokter__btn_tambahkan_poli</name>
   <tag></tag>
   <elementGuidId>b4b9d590-aa33-4ea4-ae18-bf854938df86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_btn_tambahkan_poli']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_btn_tambahkan_poli</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Tambahkan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>606b5afc-ad0f-4d91-a56c-2f63ae7b936f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>397f8527-8eef-496e-a778-a77f3656eb88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_btn_tambahkan_poli</value>
      <webElementGuid>b76587af-53a6-41c4-a21d-529cff761737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_btn_tambahkan_poli</value>
      <webElementGuid>47270289-9be3-4943-a117-73391376c5d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Tambahkan</value>
      <webElementGuid>d92948a5-9804-4d24-b53d-fa61528c884f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>fn_tambahkan_poli()</value>
      <webElementGuid>7a122690-1684-4a3b-8347-aaa62206afe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_btn_tambahkan_poli&quot;)</value>
      <webElementGuid>9d71d333-1905-4c57-a048-25c30b8ed661</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_btn_tambahkan_poli']</value>
      <webElementGuid>1f18c012-1a3e-472f-a6e3-16f3fe18ce40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='_tr_poli_dept']/td/input[6]</value>
      <webElementGuid>43cb3a88-7a4c-435e-bca9-1d03817db6cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input[6]</value>
      <webElementGuid>e2b87766-d95c-40e3-b313-06f2881673d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = '_btn_tambahkan_poli' and @name = '_btn_tambahkan_poli']</value>
      <webElementGuid>39c0be51-572b-4a70-8c1c-737c078b5ded</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
