<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Lain-lainPerum 1Perum 2Perum 3Perum _782d7a</name>
   <tag></tag>
   <elementGuidId>351cefbf-805f-4e11-9357-8410be1d20d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Perumahan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Perumahan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Rekam Medis&quot;s >> #Perumahan</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7ddc7862-d183-4bb8-a05c-a625473f1b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Perumahan</value>
      <webElementGuid>6fba53eb-3317-431a-a7e4-34a729d53545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Perumahan</value>
      <webElementGuid>3886263d-3897-4130-adad-6f049201eb15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>$('#Alamat','#_frm_mr_baru').focus()</value>
      <webElementGuid>565475bd-0fc4-45f6-878e-5979c71e6f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lain-lainPerum 1Perum 2Perum 3Perum 4Perumahan Alam SuteraPerumahan ArcadiaPerumahan Bandara MasPerumahan Banjar WijayaPerumahan Batu Ceper IndahPerumahan Binong PermaiPerumahan BonaPerumahan Bumi Mas RayaPerumahan Cimone Mas PermaiPerumahan Cipondoh MakmurPerumahan Dasana IndahPerumahan Duta BandaraPerumahan Duta GardenPerumahan Gading SerpongPerumahan Graha Raya residencePerumahan KehakimanPerumahan Kelapa DuaPerumahan Liga Mas RegencyPerumahan MahkotamasPerumahan Medang lestariPerumahan ModernlandPerumahan Mutiara GarudaPerumahan Palem SemiPerumahan Permata MedangPerumahan Pinang Griya PermaiPerumahan Pondok Indah MakmurPerumahan PorisPerumahan Puri MetropolitanPerumahan SeknegPerumahan Serpong ParkPerumahan Taman CibodasPerumahan Taman Kota BumiPerumahan Taman RoyalPerumahan Victoria ParkPerumahan vila Mutiara SerpongPerumahan Villa IlhamiPerumahan Villa Melati MasPerumahan Villa Tomang</value>
      <webElementGuid>7fa7de2b-0303-4a27-97a3-f9f68cffde16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_frm_mr_baru&quot;)/table[@class=&quot;tabel&quot;]/tbody[1]/tr[22]/td[2]/select[@id=&quot;Perumahan&quot;]</value>
      <webElementGuid>52e9af04-b832-4ad7-93cd-974008936b44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Perumahan']</value>
      <webElementGuid>2ff24225-381b-4da0-8920-b32c4bda416b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='_frm_mr_baru']/table/tbody/tr[22]/td[2]/select</value>
      <webElementGuid>0a1b5cc5-daa2-4eb0-ad8d-b31e17c9f9fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perumahan:'])[1]/following::select[1]</value>
      <webElementGuid>3bfe5991-3b00-4f83-9c5a-fe6a76fac430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='• harus diisi'])[15]/following::select[1]</value>
      <webElementGuid>887f6528-45c5-40c8-b32e-f3d61893a161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='• harus diisi'])[16]/preceding::select[1]</value>
      <webElementGuid>2f77f50f-3a59-4460-9145-793117cb8b75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat:'])[2]/preceding::select[1]</value>
      <webElementGuid>a96417b4-26e6-42bf-aee1-c1d43c66e75f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[22]/td[2]/select</value>
      <webElementGuid>c87d783f-13a9-4409-97b8-1bdb746aae87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Perumahan' and @name = 'Perumahan' and (text() = 'Lain-lainPerum 1Perum 2Perum 3Perum 4Perumahan Alam SuteraPerumahan ArcadiaPerumahan Bandara MasPerumahan Banjar WijayaPerumahan Batu Ceper IndahPerumahan Binong PermaiPerumahan BonaPerumahan Bumi Mas RayaPerumahan Cimone Mas PermaiPerumahan Cipondoh MakmurPerumahan Dasana IndahPerumahan Duta BandaraPerumahan Duta GardenPerumahan Gading SerpongPerumahan Graha Raya residencePerumahan KehakimanPerumahan Kelapa DuaPerumahan Liga Mas RegencyPerumahan MahkotamasPerumahan Medang lestariPerumahan ModernlandPerumahan Mutiara GarudaPerumahan Palem SemiPerumahan Permata MedangPerumahan Pinang Griya PermaiPerumahan Pondok Indah MakmurPerumahan PorisPerumahan Puri MetropolitanPerumahan SeknegPerumahan Serpong ParkPerumahan Taman CibodasPerumahan Taman Kota BumiPerumahan Taman RoyalPerumahan Victoria ParkPerumahan vila Mutiara SerpongPerumahan Villa IlhamiPerumahan Villa Melati MasPerumahan Villa Tomang' or . = 'Lain-lainPerum 1Perum 2Perum 3Perum 4Perumahan Alam SuteraPerumahan ArcadiaPerumahan Bandara MasPerumahan Banjar WijayaPerumahan Batu Ceper IndahPerumahan Binong PermaiPerumahan BonaPerumahan Bumi Mas RayaPerumahan Cimone Mas PermaiPerumahan Cipondoh MakmurPerumahan Dasana IndahPerumahan Duta BandaraPerumahan Duta GardenPerumahan Gading SerpongPerumahan Graha Raya residencePerumahan KehakimanPerumahan Kelapa DuaPerumahan Liga Mas RegencyPerumahan MahkotamasPerumahan Medang lestariPerumahan ModernlandPerumahan Mutiara GarudaPerumahan Palem SemiPerumahan Permata MedangPerumahan Pinang Griya PermaiPerumahan Pondok Indah MakmurPerumahan PorisPerumahan Puri MetropolitanPerumahan SeknegPerumahan Serpong ParkPerumahan Taman CibodasPerumahan Taman Kota BumiPerumahan Taman RoyalPerumahan Victoria ParkPerumahan vila Mutiara SerpongPerumahan Villa IlhamiPerumahan Villa Melati MasPerumahan Villa Tomang')]</value>
      <webElementGuid>c7766490-52ea-4eb2-b080-fe5af323139c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
