<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Pilih Propinsi - AcehSumatera Utar_4cfab2</name>
   <tag></tag>
   <elementGuidId>aa915a07-ef77-418d-a62f-c017fc13923e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='PropinsiID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PropinsiID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PropinsiID</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f6538b78-6703-4283-a734-991609d54aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PropinsiID</value>
      <webElementGuid>503afa47-755a-4431-9b7f-b893f01046bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PropinsiID</value>
      <webElementGuid>7d3a76d0-9551-439a-ac72-512e28831c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>fn_change_province(this.value, 'add')</value>
      <webElementGuid>df1ffecc-1853-42b0-9fda-7c34c5c76134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_width border-rounded border-grey padding-5px cursor-pointer</value>
      <webElementGuid>4b451c7b-9d89-43ff-b24e-cc6c769e4569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> - Pilih Propinsi - AcehSumatera UtaraSumatera BaratRiauJambiSumatera SelatanBengkuluLampungKepulauan Bangka BelitungKepulauan RiauDKI JakartaJawa BaratJawa TengahDI YogyakartaJawa TimurBantenBaliNusa Tenggara BaratNusa Tenggara TimurKalimantan BaratKalimantan TengahKalimantan SelatanKalimantan TimurKalimantan UtaraSulawesi UtaraSulawesi TengahSulawesi SelatanSulawesi TenggaraGorontaloSulawesi BaratMalukuMaluku UtaraPapua BaratPapua</value>
      <webElementGuid>c6184a0f-9070-4021-ac41-6208142afe97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PropinsiID&quot;)</value>
      <webElementGuid>556eccec-53ed-481f-b901-837018001b00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='PropinsiID']</value>
      <webElementGuid>0faf7c88-088f-4016-87d9-df6ed967819b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='span_prov']/select</value>
      <webElementGuid>eaf4a215-52d0-4945-968b-0f97982a4288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Propinsi:'])[1]/following::select[1]</value>
      <webElementGuid>c9265097-18e1-426b-b99e-d64814e0a390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='• harus diisi'])[11]/following::select[1]</value>
      <webElementGuid>ef098dca-6737-444b-8a65-5b3158b8b33d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='• harus diisi'])[12]/preceding::select[1]</value>
      <webElementGuid>f2fd3e84-d844-43c0-9207-de529e1d0fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kabupaten / Kota:'])[1]/preceding::select[1]</value>
      <webElementGuid>f13bb6e1-4259-45ca-9e87-f46ea6a8509b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[18]/td[2]/span/select</value>
      <webElementGuid>ef848e5d-c338-41b5-96ca-a36cef962a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'PropinsiID' and @name = 'PropinsiID' and (text() = ' - Pilih Propinsi - AcehSumatera UtaraSumatera BaratRiauJambiSumatera SelatanBengkuluLampungKepulauan Bangka BelitungKepulauan RiauDKI JakartaJawa BaratJawa TengahDI YogyakartaJawa TimurBantenBaliNusa Tenggara BaratNusa Tenggara TimurKalimantan BaratKalimantan TengahKalimantan SelatanKalimantan TimurKalimantan UtaraSulawesi UtaraSulawesi TengahSulawesi SelatanSulawesi TenggaraGorontaloSulawesi BaratMalukuMaluku UtaraPapua BaratPapua' or . = ' - Pilih Propinsi - AcehSumatera UtaraSumatera BaratRiauJambiSumatera SelatanBengkuluLampungKepulauan Bangka BelitungKepulauan RiauDKI JakartaJawa BaratJawa TengahDI YogyakartaJawa TimurBantenBaliNusa Tenggara BaratNusa Tenggara TimurKalimantan BaratKalimantan TengahKalimantan SelatanKalimantan TimurKalimantan UtaraSulawesi UtaraSulawesi TengahSulawesi SelatanSulawesi TenggaraGorontaloSulawesi BaratMalukuMaluku UtaraPapua BaratPapua')]</value>
      <webElementGuid>3a27983a-b6d5-4c59-a2a0-84402e640da3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
