<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Pilih Kabupaten  Kota - Kab. Pande_dd3b8c</name>
   <tag></tag>
   <elementGuidId>9170757e-696a-4b30-a94f-774f813bb619</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='KotaID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#KotaID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#KotaID</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f3ea442e-668e-4c46-ba0f-083dec7b6522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>KotaID</value>
      <webElementGuid>f7d55e5d-a0a8-4e01-a3cf-08dfd64fd9a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>KotaID</value>
      <webElementGuid>f0d9ad26-0dc7-4db6-8838-225d7dbacbda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>fn_change_kabupatenkota(this.value, 'add')</value>
      <webElementGuid>695bcc04-2a2c-469b-9e70-45d107b0bab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_width border-rounded border-grey padding-5px cursor-pointer</value>
      <webElementGuid>f9d7a5ce-d806-4f17-861e-bce242be7210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> - Pilih Kabupaten / Kota - Kab. PandeglangKab. LebakKab. TangerangKab. SerangKota TangerangKota CilegonKota SerangKota Tangerang Selatan</value>
      <webElementGuid>62d35d21-bcea-4be4-a134-7fc66e7527d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;KotaID&quot;)</value>
      <webElementGuid>c2e7e96c-4458-4049-9418-a4b160d95be0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='KotaID']</value>
      <webElementGuid>8525f245-0072-4a72-82b4-2d5c6fb3321d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='span_kotkab']/select</value>
      <webElementGuid>effcc9c2-a0da-4879-bb60-c31716d3822e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kabupaten / Kota:'])[1]/following::select[1]</value>
      <webElementGuid>1d3be7fa-85e1-466b-9260-0330aae1d3ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='• harus diisi'])[12]/following::select[1]</value>
      <webElementGuid>86ac5f4a-51e0-4242-b622-61a15d71c65f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='• harus diisi'])[13]/preceding::select[1]</value>
      <webElementGuid>627431a3-5086-4895-954f-45863109cee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan:'])[1]/preceding::select[1]</value>
      <webElementGuid>534442c7-974b-4357-b0a8-2d36136add13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[19]/td[2]/span/select</value>
      <webElementGuid>0359e968-0f89-4dbf-9f0d-70c62d5db1f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'KotaID' and @name = 'KotaID' and (text() = ' - Pilih Kabupaten / Kota - Kab. PandeglangKab. LebakKab. TangerangKab. SerangKota TangerangKota CilegonKota SerangKota Tangerang Selatan' or . = ' - Pilih Kabupaten / Kota - Kab. PandeglangKab. LebakKab. TangerangKab. SerangKota TangerangKota CilegonKota SerangKota Tangerang Selatan')]</value>
      <webElementGuid>70b45ca8-1507-477d-a526-28dd129c12e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
