<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_KITASKartu Tanda Penduduk -- KTPPasp_23ed04</name>
   <tag></tag>
   <elementGuidId>9ca651ca-9a16-4136-9a47-716424fb1e82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='JenisNomerSosial']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#JenisNomerSosial</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Rekam Medis&quot;s >> #JenisNomerSosial</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>44f4265b-183d-443f-86d6-bf2b1be963cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>JenisNomerSosial</value>
      <webElementGuid>141a8d54-f366-4790-8baf-0cf87201e455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>JenisNomerSosial</value>
      <webElementGuid>ad1e281b-03c7-4ebe-906d-ef8fc1cc89cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>$('#NomerSosial','#_frm_mr_baru').val('');</value>
      <webElementGuid>da12e470-9973-4782-aee2-4dfb49d06120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KITASKartu Tanda Penduduk -- KTPPasporSurat Ijin Mengemudi -- SIM</value>
      <webElementGuid>3d082427-bfa4-480f-8125-7106cc19d55e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_frm_mr_baru&quot;)/table[@class=&quot;tabel&quot;]/tbody[1]/tr[15]/td[2]/select[@id=&quot;JenisNomerSosial&quot;]</value>
      <webElementGuid>b4a6f980-8ed1-479e-b199-4b4253f85319</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='JenisNomerSosial']</value>
      <webElementGuid>b33cb9b6-a09c-4493-8a4a-4dffeffcbeed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='_frm_mr_baru']/table/tbody/tr[15]/td[2]/select</value>
      <webElementGuid>e025350f-fd76-4e4e-b11c-7acb7497a661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomer Identitas:'])[1]/following::select[1]</value>
      <webElementGuid>9fe4e1fc-00d5-40ad-8afc-5ee8298ba363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='• harus diisi'])[8]/following::select[1]</value>
      <webElementGuid>af8006fe-77f0-4bc1-a86b-a6eb03ddb663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='• harus diisi'])[9]/preceding::select[1]</value>
      <webElementGuid>733b4b69-5622-4ab6-b1b5-f21cf4d81daf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kewarganegaraan'])[1]/preceding::select[1]</value>
      <webElementGuid>d8634a22-2717-47bd-b6f4-5c2706d807fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[15]/td[2]/select</value>
      <webElementGuid>aeae3394-3278-4592-abc7-5684fa110bf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'JenisNomerSosial' and @name = 'JenisNomerSosial' and (text() = 'KITASKartu Tanda Penduduk -- KTPPasporSurat Ijin Mengemudi -- SIM' or . = 'KITASKartu Tanda Penduduk -- KTPPasporSurat Ijin Mengemudi -- SIM')]</value>
      <webElementGuid>fc22b6a7-5444-4f11-9595-4b303898151d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
