<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Pilih Kelurahan - JayantiPasir Mun_3830bd</name>
   <tag></tag>
   <elementGuidId>7da1046d-c4db-434e-86b1-b7927fbbf181</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='KelurahanID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#KelurahanID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#KelurahanID</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2cd65d8d-66d6-402b-a807-3701805ae911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>KelurahanID</value>
      <webElementGuid>4a4eff74-653f-424d-b736-4f9a89e243ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>KelurahanID</value>
      <webElementGuid>74498674-edf0-432b-aa6f-ba307c4bde7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>fn_change_kelurahan(this.value, 'add')</value>
      <webElementGuid>2895a074-b927-490f-b0a5-8721152269b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_width border-rounded border-grey padding-5px cursor-pointer</value>
      <webElementGuid>123cfdc3-fb44-4d6c-bdde-ec457c6a74a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> - Pilih Kelurahan - JayantiPasir MuncangSumur BandungCikandePasir GintungPangkatDang DeurPabuaran</value>
      <webElementGuid>dc64d6a4-297a-4dab-87a4-ed7f95f54cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;KelurahanID&quot;)</value>
      <webElementGuid>fe7a537c-74c9-416a-938b-462eb4a281b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='KelurahanID']</value>
      <webElementGuid>c9bd8f2d-5339-4de9-b272-a18d3f3d50ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='span_kelurahan']/select</value>
      <webElementGuid>e5fb442f-0d74-45e2-a18b-09146f9d17f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelurahan / Kode Pos:'])[1]/following::select[1]</value>
      <webElementGuid>146b6d8b-fa62-4510-a835-5df3077d0494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='• harus diisi'])[14]/following::select[1]</value>
      <webElementGuid>568e7154-301d-427e-afd6-38605dfe1671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='• harus diisi'])[15]/preceding::select[1]</value>
      <webElementGuid>2b5fa9ec-cbb0-4565-9839-f213eff6f756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perumahan:'])[1]/preceding::select[1]</value>
      <webElementGuid>38b68865-4ef1-42d1-a185-3ee53ae2a926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[21]/td[2]/span/select</value>
      <webElementGuid>ac5bd832-8bf2-4c5b-be30-7b633bcf1d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'KelurahanID' and @name = 'KelurahanID' and (text() = ' - Pilih Kelurahan - JayantiPasir MuncangSumur BandungCikandePasir GintungPangkatDang DeurPabuaran' or . = ' - Pilih Kelurahan - JayantiPasir MuncangSumur BandungCikandePasir GintungPangkatDang DeurPabuaran')]</value>
      <webElementGuid>1b895720-9728-4484-8b64-35ad9762ec69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
