<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Belum MenikahCeraiMenikah</name>
   <tag></tag>
   <elementGuidId>5117bf8e-9409-4460-a699-c05fabc84313</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='StatusPerkawinan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#StatusPerkawinan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Rekam Medis&quot;s >> #StatusPerkawinan</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6e32d6e7-2ed7-43be-8125-f40681443f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>StatusPerkawinan</value>
      <webElementGuid>9b3b4728-528b-46a8-960b-42e57558b5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>StatusPerkawinan</value>
      <webElementGuid>f48cce77-ccf8-4961-8493-6aca47ab5460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Belum MenikahCeraiMenikah</value>
      <webElementGuid>26f29415-a1a6-4dfd-a769-9a26bc1f585f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_frm_mr_baru&quot;)/table[@class=&quot;tabel&quot;]/tbody[1]/tr[14]/td[2]/select[@id=&quot;StatusPerkawinan&quot;]</value>
      <webElementGuid>364fe1fa-4577-4c3a-b415-f0efa5082542</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='StatusPerkawinan']</value>
      <webElementGuid>15642492-1b30-4692-a306-925944c8d0ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='_frm_mr_baru']/table/tbody/tr[14]/td[2]/select</value>
      <webElementGuid>9151ba35-d534-49b9-b1f9-2ea9a6b5eaee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Perkawinan:'])[1]/following::select[1]</value>
      <webElementGuid>002fe545-f8dc-4560-b481-f64cf0080d71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='• harus diisi'])[7]/following::select[1]</value>
      <webElementGuid>943607ff-3c50-464c-9dc1-97d5b3d64f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='• harus diisi'])[8]/preceding::select[1]</value>
      <webElementGuid>55df716a-92f2-41c3-b898-606b3c7c73a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomer Identitas:'])[1]/preceding::select[1]</value>
      <webElementGuid>97271cf5-7b25-4406-a5a9-a31e7d21e2f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[14]/td[2]/select</value>
      <webElementGuid>d74f511c-1d4e-4b6c-85e8-f31f86e43c7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'StatusPerkawinan' and @name = 'StatusPerkawinan' and (text() = 'Belum MenikahCeraiMenikah' or . = 'Belum MenikahCeraiMenikah')]</value>
      <webElementGuid>446fd523-0321-4551-b285-a25537fad81a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
