<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PagiSiangMalam</name>
   <tag></tag>
   <elementGuidId>0710e268-9723-44a5-bea5-dda027f9b6ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='_WaktuShiftID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_WaktuShiftID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;_WaktuShiftID&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f3e94f94-270c-4e81-887a-6a2a90f9997a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_WaktuShiftID</value>
      <webElementGuid>a616ede7-601a-40a0-b416-e89cf2a10b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_WaktuShiftID</value>
      <webElementGuid>d6868258-f8a1-4d55-a246-7ca9494f9e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;
Pagi
Siang
Malam
</value>
      <webElementGuid>d0b420ab-f356-43a6-8707-77b379242df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_WaktuShiftID&quot;)</value>
      <webElementGuid>8ab656fd-c2f1-4195-b204-76c75dc0a86f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='_WaktuShiftID']</value>
      <webElementGuid>79e77c98-a0e8-494a-9104-d25bd4797dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='openshift']/table/tbody/tr[2]/td[2]/select</value>
      <webElementGuid>5e1e83c0-b22b-46b3-87e2-efc078a500dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/preceding::select[1]</value>
      <webElementGuid>8f3bb027-67a0-465e-817e-35d0bef63399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rekam Medis'])[1]/preceding::select[1]</value>
      <webElementGuid>da822680-7866-432d-80d5-cce6611ed709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='&lt;']/parent::*</value>
      <webElementGuid>2f731399-6a1c-47c5-b73d-0b194fbf8335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/select</value>
      <webElementGuid>a58fd99a-f8ca-4fc9-b54d-551441988cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '_WaktuShiftID' and @name = '_WaktuShiftID' and (text() = '&lt;
Pagi
Siang
Malam
' or . = '&lt;
Pagi
Siang
Malam
')]</value>
      <webElementGuid>33861686-cb0b-4c3c-ad58-4e34ae861ae4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
