<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Rawat Jalan</name>
   <tag></tag>
   <elementGuidId>cc8445d6-e266-4548-b2e5-5665d5cffd52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='_GroupShiftID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_GroupShiftID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;_GroupShiftID&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>af8a27c8-2b19-4c2b-a944-1d083d9312d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_GroupShiftID</value>
      <webElementGuid>55e8e26d-d0f4-438d-aba5-2a10b46921f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_GroupShiftID</value>
      <webElementGuid>a8057fc5-6299-48eb-b1ce-cd218d7b1d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Rawat Jalan
</value>
      <webElementGuid>84b57520-56ea-4ab3-8518-ae9dc2623450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_GroupShiftID&quot;)</value>
      <webElementGuid>1c01b166-f136-4d1b-b44b-c59bddbda8eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='_GroupShiftID']</value>
      <webElementGuid>77be529c-2e08-48de-868f-325f66332f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='openshift']/table/tbody/tr/td[2]/select</value>
      <webElementGuid>17b7bf9e-f7fc-46b0-aa9d-46a27ecd77ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jika ingin membuka shift baru, silakan isi form di bawah ini.'])[1]/following::select[1]</value>
      <webElementGuid>5d7a4f32-2884-46d2-8b42-ff7a62af82e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/table/tbody/tr/td[2]/select</value>
      <webElementGuid>389e90ec-1b47-4dcb-a289-b5e88b500d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '_GroupShiftID' and @name = '_GroupShiftID' and (text() = '
Rawat Jalan
' or . = '
Rawat Jalan
')]</value>
      <webElementGuid>b8327438-9cf5-4b57-b296-c3a919714083</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
