<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Alamat_Alamat</name>
   <tag></tag>
   <elementGuidId>4ef8bf2d-2597-4db1-99fd-581112d3691a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Alamat']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(23) > td:nth-of-type(2) > #Alamat</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Rekam Medis&quot;s >> #Alamat</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>434be2d2-9fb6-4d63-9f4c-35d0109cfe6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Alamat</value>
      <webElementGuid>b38f1322-2354-477f-b935-886f6706c62d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Alamat</value>
      <webElementGuid>2d74ea78-9844-4bb2-a004-66932dbae019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_frm_mr_baru&quot;)/table[@class=&quot;tabel&quot;]/tbody[1]/tr[23]/td[2]/textarea[@id=&quot;Alamat&quot;]</value>
      <webElementGuid>fad0ea1b-6e11-4724-a13d-c7ac8d7befa0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Alamat']</value>
      <webElementGuid>ee40dc74-f5a5-40b7-b053-9e93087b1fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='_frm_mr_baru']/table/tbody/tr[23]/td[2]/textarea</value>
      <webElementGuid>2b05d6b2-b6be-46b6-80b8-4866ea6a5d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[23]/td[2]/textarea</value>
      <webElementGuid>1de6a13f-b5ef-4728-925c-9a5d833685ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Alamat' and @name = 'Alamat']</value>
      <webElementGuid>c6bac64a-4be6-452d-ac6f-0c679dce78a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
