<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cari Pasien__btn_pendaftaran_rj</name>
   <tag></tag>
   <elementGuidId>4be62f24-558b-4549-99aa-15b487a319e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_btn_pendaftaran_rj']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_btn_pendaftaran_rj</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Pendaftaran RJ (F1)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>312ac45a-2bf0-40d1-8597-dc9a9d1264e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>018e350f-93f1-46e4-a115-dc25940e0211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_btn_pendaftaran_rj</value>
      <webElementGuid>9d5773eb-65e9-4b79-89c8-9c6e47f4a2b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_btn_pendaftaran_rj</value>
      <webElementGuid>b5ddf057-a3f4-4d7a-afb9-1213ab4beca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Pendaftaran RJ (F1)</value>
      <webElementGuid>7445779c-5061-400d-a92b-8610a8a391aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>fn_pendaftaran('rj')</value>
      <webElementGuid>5459b1b8-cc12-400e-80dd-ffa155c77bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button ui-widget ui-state-default ui-corner-right ui-state-hover ui-state-focus</value>
      <webElementGuid>20457b99-dadb-4e5e-bd4e-dbb0f587fe55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>985fdd88-0e88-43be-9d87-b9484512c267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>175839d2-6188-4e5c-8273-b2c3f8ab2404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_btn_pendaftaran_rj&quot;)</value>
      <webElementGuid>9da7d863-6e05-49af-80a0-88cea581e089</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_btn_pendaftaran_rj']</value>
      <webElementGuid>0624e99c-639a-4829-b433-f13a2423bc05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_div_btn_rj']/input[3]</value>
      <webElementGuid>3b625d2f-ecbf-4bb6-9835-e9aa274e4d7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[3]</value>
      <webElementGuid>19127a95-0127-4777-b789-568833a15b8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = '_btn_pendaftaran_rj' and @name = '_btn_pendaftaran_rj']</value>
      <webElementGuid>4b52dc42-be9a-4b8e-861b-81540dda7d20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
