<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Rawat Jalan</name>
   <tag></tag>
   <elementGuidId>2ccb1f71-f9ee-462e-b832-d03d6f52a662</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='_GroupShiftID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_GroupShiftID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;_GroupShiftID&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9eb1279f-c74b-40c2-b480-b09ef022acd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_GroupShiftID</value>
      <webElementGuid>277f1230-00da-490b-949c-fdbc4566bb44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_GroupShiftID</value>
      <webElementGuid>55bbc117-b159-4cf9-b510-229b1eabe8a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Rawat Jalan
</value>
      <webElementGuid>54f4fa3e-824e-407b-ac79-31d3416c1f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_GroupShiftID&quot;)</value>
      <webElementGuid>8ac062f2-32c0-470f-b7fb-bbbf91da9beb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='_GroupShiftID']</value>
      <webElementGuid>94bcd0b6-57cc-48b3-b3ee-3a4b3cdfb3de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='openshift']/table/tbody/tr/td[2]/select</value>
      <webElementGuid>35ab2e45-f419-45f6-92ab-e7e69352d08c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jika ingin membuka shift baru, silakan isi form di bawah ini.'])[1]/following::select[1]</value>
      <webElementGuid>737001a7-3723-4048-afb3-c8549ea1a268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/table/tbody/tr/td[2]/select</value>
      <webElementGuid>6140a0b0-0365-457d-bd8e-e74e1d4b654c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '_GroupShiftID' and @name = '_GroupShiftID' and (text() = '
Rawat Jalan
' or . = '
Rawat Jalan
')]</value>
      <webElementGuid>cfbbcfe2-005e-4990-8901-367e00451e3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
