<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PagiSiangMalam</name>
   <tag></tag>
   <elementGuidId>eefa271d-4af8-496a-8b8b-331e2c773315</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='_WaktuShiftID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_WaktuShiftID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;_WaktuShiftID&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>eecd33ec-0f3a-4841-a651-c45edf4b3299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_WaktuShiftID</value>
      <webElementGuid>69b521c2-22f1-4795-9b14-1dbda02b0a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_WaktuShiftID</value>
      <webElementGuid>b0989875-ae3a-4e12-8696-aa1bb4adf275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;
Pagi
Siang
Malam
</value>
      <webElementGuid>08b1c363-011c-4206-9704-77d7a3baef86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_WaktuShiftID&quot;)</value>
      <webElementGuid>2eb7cb92-cd86-4de2-a9de-2d4676b2d698</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='_WaktuShiftID']</value>
      <webElementGuid>a2c189ba-2eb2-4317-969f-38c2e952ef14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='openshift']/table/tbody/tr[2]/td[2]/select</value>
      <webElementGuid>71c56837-ace1-4c43-9319-27c792e8eeb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/preceding::select[1]</value>
      <webElementGuid>c545f639-4734-436d-a76d-af8a5e1f8e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rekam Medis'])[1]/preceding::select[1]</value>
      <webElementGuid>cac5d48c-b6c8-46c3-af62-16bd77b47984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='&lt;']/parent::*</value>
      <webElementGuid>c88623f0-3f05-44d8-9421-fd96bf8dc624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/select</value>
      <webElementGuid>a3cb96df-c6ab-428f-a5b6-62f3c0fc567b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '_WaktuShiftID' and @name = '_WaktuShiftID' and (text() = '&lt;
Pagi
Siang
Malam
' or . = '&lt;
Pagi
Siang
Malam
')]</value>
      <webElementGuid>dd400788-e15c-486a-9a69-28bc2d19bb35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
