<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PagiSiangMalam</name>
   <tag></tag>
   <elementGuidId>0b159874-9a81-4da4-9cfd-173bb86ad185</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='_WaktuShiftID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_WaktuShiftID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;_WaktuShiftID&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c781b12b-bab6-4eb6-a8ed-2c12e88f42a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_WaktuShiftID</value>
      <webElementGuid>9754ef03-fc1e-4ffd-91ea-b973f84ca1bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_WaktuShiftID</value>
      <webElementGuid>d8effc14-6f18-4aa8-ad65-8e4aae2defd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;
Pagi
Siang
Malam
</value>
      <webElementGuid>b03321de-e9b9-4040-86cf-c82266b84ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_WaktuShiftID&quot;)</value>
      <webElementGuid>8cf79be0-bede-4d86-8baa-69826939b8fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='_WaktuShiftID']</value>
      <webElementGuid>ef422096-d890-4f6c-9b33-aed6d4e9dfff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='openshift']/table/tbody/tr[2]/td[2]/select</value>
      <webElementGuid>bef102b5-ba23-42f6-a610-21e6be20ed96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/preceding::select[1]</value>
      <webElementGuid>38a36a7b-500c-4715-a5c4-24a499b0687c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rekam Medis'])[1]/preceding::select[1]</value>
      <webElementGuid>d34abb07-99ba-46c5-a233-9d5981e01deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='&lt;']/parent::*</value>
      <webElementGuid>a1416c21-966f-4f16-83b4-4c9d42db2a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/select</value>
      <webElementGuid>475c3e38-dc0d-430c-8fd6-0a13736d1555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '_WaktuShiftID' and @name = '_WaktuShiftID' and (text() = '&lt;
Pagi
Siang
Malam
' or . = '&lt;
Pagi
Siang
Malam
')]</value>
      <webElementGuid>9431c3ab-100b-426c-b6fc-0129e9dc8f78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
