<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Rawat Jalan</name>
   <tag></tag>
   <elementGuidId>05f68eb7-d919-4668-bd3d-a5b76120eecf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='_GroupShiftID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_GroupShiftID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;_GroupShiftID&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6758fbcd-035a-46dd-aba8-7c384cde6729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_GroupShiftID</value>
      <webElementGuid>47e47545-9662-4093-81c1-c88848ee82ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_GroupShiftID</value>
      <webElementGuid>272dd9c1-1ae4-4194-9bb5-4aa917f5401a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Rawat Jalan
</value>
      <webElementGuid>c50bd4aa-a045-4bbe-8d11-cbf896b39c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_GroupShiftID&quot;)</value>
      <webElementGuid>e5e77be1-e5be-4a50-b656-cfac0a70837a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='_GroupShiftID']</value>
      <webElementGuid>e2e1c047-d223-405d-8da6-562e8201384a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='openshift']/table/tbody/tr/td[2]/select</value>
      <webElementGuid>170398af-711c-4cce-9525-4a1f8e73dddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jika ingin membuka shift baru, silakan isi form di bawah ini.'])[1]/following::select[1]</value>
      <webElementGuid>7fcbeed9-e178-4d70-8e21-a98ecc704718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/table/tbody/tr/td[2]/select</value>
      <webElementGuid>57d8b7a6-2bf9-4bf0-8d6d-653c5749a055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '_GroupShiftID' and @name = '_GroupShiftID' and (text() = '
Rawat Jalan
' or . = '
Rawat Jalan
')]</value>
      <webElementGuid>d68665b6-52a1-442b-b151-fe992cda3b1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
